const data = {
  products: [
    {
      name: 'TAEGESSCHU',
      slug: 'TAEGESSCHU',
      category: 'Fantasy',
      image: '/images/Art-1.webp',
      price: 630,
      countInStock: 10,
      Artist: 'ARCHAN NAIR',
      rating: 4.5,
      numReviews: 10,
      description: 'explores the macro and micro spaces between and around us',
    },
    {
      name: 'LUSH',
      slug: 'LUSH',
      category: 'Fantasy',
      image: '/images/Art-2.webp',
      price: 700,
      countInStock: 5,
      Artist: 'JOHNNY GANTA',
      rating: 4.0,
      numReviews: 1,
      description: 'Lush is a digitially constructed collage dreamscape that works as a heightened sensory vehicle for the mystical side of reality',
    },
    {
      name: 'TIFFIN TOWERS',
      slug: 'TIFFIN TOWERS',
      category: 'Insightful',
      image: '/images/tiffin-towers.webp',
      price: 750,
      countInStock: 6,
      Artist: 'KUNAL ANAND',
      rating: 3.5,
      numReviews: 2,
      description: ' an alternate reality version of Mumbai that is still just as oddly zen while being fully packed.',
    },
    {
      name: 'FORTUNE FEATHERS',
      slug: 'FORTUNE FEATHERS',
      category: 'Animals',
      image: '/images/fortune-feathers.webp',
      price: 560,
      countInStock: 3,
      Artist: 'MIRA MALHOTRA',
      rating: 4.0,
      numReviews: 3,
      description: " parrot fortune teller is under great pressure from the weight of so many people's expectations.",
    },
    {
      name: 'LIFE IN A FISH BOWL',
      slug: 'LIFE IN A FISH BOWL',
      category: 'Animals',
      image: '/images/life-in-a-fish-bowl.webp',
      price: 630,
      countInStock: 8,
      Artist: 'SHRUTHI VENKATARAMAN',
      rating: 4.0,
      numReviews: 4,
      description: ' cats who trouble little fish in their bowls , explores how global warming could turn the tables in this relationship.',
    },
    {
      name: 'ELECTRONICA',
      slug: 'ELECTRONICA',
      category: 'Insightful',
      image: '/images/electronica.webp',
      price: 2100,
      countInStock: 10,
      Artist: 'RESHIDEV RK',
      rating: 4.0,
      numReviews: 5,
      description: 'Basic Love Of Things, is a mixed media and audio visual performance ensemble',
    },
    {
      name: 'SO SAID DALI',
      slug: 'SO SAID DALI',
      category: 'Nostalgic',
      image: '/images/so-said-dali.webp',
      price: 630,
      countInStock: 7,
      Artist: 'SHEEHIJ KAUL',
      rating: 4.0,
      numReviews: 6,
      description: "When we're asleep in this world, we are awake in another",
    },{
      name: 'FLOWERS IN HER HAIR',
      slug: 'FLOWERS IN HER HAIR',
      category: 'Nostalgic',
      image: '/images/flowers-in-her-hair.webp',
      price: 670,
      countInStock: 6,
      Artist: 'MUHAMMED SAJID',
      rating: 4.0,
      numReviews: 7,
      description: 'Indian women and men that tell their stories. He gives us a glimpse of the feisty dame with flowers in her hair',
    },
    {
      name: 'BREWING WORK FROM HOME',
      slug: 'BREWING WORK FROM HOME',
      category: 'Figurative',
      image: '/images/brewing-work-form-home.webp',
      price: 700,
      countInStock: 16,
      Artist: 'RANGANATH KRISHNAMANI',
      rating: 4.0,
      numReviews: 8,
      description: 'finds us finding our own little comfort work corners at home to get work done',
    },
    {
      name: 'TAKE ME TO WONDERLAND',
      slug: 'TAKE ME TO WONDERLAND',
      category: 'Figurative',
      image: '/images/take-me-to-wonderland.webp',
      price: 640,
      countInStock: 12,
      Artist: 'KUNEL GAUR',
      rating: 4.0,
      numReviews: 9,
      description: 'highway romance is a tribute to 150 years of Alice in Wonderland',
    },
    {
      name: 'WORSHIP',
      slug: 'WORSHIP',
      category: 'Characters',
      image: '/images/worship.webp',
      price: 560,
      countInStock: 12,
      Artist: 'FEARLESS COLLECTIVE',
      rating: 4.0,
      numReviews: 11,
      description: 'Durga, goddess of strength, upon her consort, a tiger, and a little girl and her cat looking up at he',
    },
    {
      name: 'HOLD THAT THOUGHT',
      slug: 'HOLD THAT THOUGHT',
      category: 'Fantasy',
      image: '/images/hold-that-thought.webp',
      price: 540,
      countInStock: 21,
      Artist: 'SHEEHIJ KAUL',
      rating: 4.0,
      numReviews: 12,
      description: 'The artwork hints at introspection and the explorative nature of our mind',
    },
    {
      name: 'SO SAID EINSTEIN',
      slug: 'SO SAID EINSTEIN',
      category: 'Characters',
      image: '/images/so-said-einstein.webp',
      price: 620,
      countInStock: 27,
      Artist: 'SHEEHIJ KAUL',
      rating: 4.0,
      numReviews: 13,
      description: ' an interpretation of the quote by Einstein: “Be a loner. That gives you time to wonder.”',
    },
    {
      name: 'VAN JOE',
      slug: 'VAN JOE',
      category: 'Nostalgic',
      image: '/images/van-joe.webp',
      price: 900,
      countInStock: 15,
      Artist: 'KUNEL GAUR',
      rating: 4.0,
      numReviews: 14,
      description: 'Van Gogh still stands as a colossal',
    },
    {
      name: 'FRAGILE DREAMS',
      slug: 'FRAGILE DREAMS',
      category: 'Nostalgic',
      image: '/images/fragile-dreams.webp',
      price: 800,
      countInStock: 14,
      Artist: 'AVINASH JAI SINGH',
      rating: 4.0,
      numReviews: 15,
      description: 'imagination',
    },
    {
      name: 'SECOND SKIN',
      slug: 'SECOND SKIN',
      category: 'Characters',
      image: '/images/second-skin.webp',
      price: 740,
      countInStock: 16,
      Artist: 'KUNAL ANAND',
      rating: 4.0,
      numReviews: 16,
      description: 'human experience will evolve, adapt and continue',
    },
    {
      name: 'DIVIDE',
      slug: 'DIVIDE',
      category: 'Nostalgic',
      image: '/images/divide.webp',
      price: 960,
      countInStock: 11,
      Artist: 'RESHIDEV RK',
      rating: 4.0,
      numReviews: 17,
      description: 'The mind is often torn between rules and dreams.',
    },
    {
      name: 'REAP',
      slug: 'REAP',
      category: 'Figurative',
      image: '/images/reap.webp',
      price: 1300,
      countInStock: 19,
      Artist: 'SHEEHIJ KAUL',
      rating: 4.0,
      numReviews: 18,
      description: 'surreal digital collage.',
    },{
      name: 'TWO IN THE BUSH',
      slug: 'TWO IN THE BUSH',
      category: 'Naure',
      image: '/images/two-in-the-bush.webp',
      price: 2100,
      countInStock: 17,
      Artist: 'SHEEHIJ KAUL',
      rating: 4.0,
      numReviews: 19,
      description: 'playful take on the age old saying — "Two in the Bush',
    },
    {
      name: 'MANGO',
      slug: 'MANGO',
      category: 'Nature',
      image: '/images/mango.webp',
      price: 730,
      countInStock: 9,
      Artist: 'RANGANATH KRISHNAMANI',
      rating: 4.0,
      numReviews: 20,
      description: 'sweet, yellow Rajapuri "aam"',
    },
  ],
};
export default data;
